Airport_App/Controllers/CityController.cs
using Airport_App_Core.Contracts;
using Airport_App_Core.Models.CityModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Airport_App.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public CityController(
            ICityService _cityServ,
            ICountryService _countryService)
        {
            cityService = _cityServ;
            countryService = _countryService;
        }

        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> AddNewCity()
        {
            AddNewCityModel city = new AddNewCityModel()
            {
                Countries = await countryService.AddAllCountries(),
            };
            return View(city);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> AddNewCity(AddNewCityModel city)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AddNewCity));
            }

            var isThere = cityService.CheckIfExist(city);
            if (isThere == true)
            {
                return RedirectToAction(nameof(AddNewCity));
            }

            await cityService.AddNewCity(city);

            return RedirectToAction(nameof(AllCities));
        }

        public async Task<IActionResult> AllCities()
        {
            return View(await cityService.AllCities());
        }

        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]

        public async Task<IActionResult> Edit(int id)
        {
            var result = await cityService.FindCity(id);
            result.Countries = await countryService.AddAllCountries();
            return View(result);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Edit (AddNewCityModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllCities));
            }
            var isThere = cityService.CheckIfExist(model);
            if (isThere == true)
            {
                return RedirectToAction(nameof(AddNewCity));
            }
            await cityService.SaveChangesAsync(model);
            return RedirectToAction(nameof(AllCities));
        }

        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Delete (int id)
        {
            await cityService.Delete(id);
            return RedirectToAction(nameof(AllCities));
        }
    }
}

Airport_App/Views/City/AddNewCity.cshtml
@model AddNewCityModel
@{
    ViewData["Title"] = "Add new city";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="mb-3">
                <label asp-for="@Model.CountryId" class="form-label"> Select Country</label>
                <select asp-for="@Model.CountryId" class="form-control">
                    @foreach (var airport in Model.Countries)
                    {
                        <option value="@airport.Id">@airport.Name</option>
                    }
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Airport_App/Views/City/AllCities.cshtml
@model List<DisplayCitiesModel>
@{
    ViewData["Title"] = "All Cities";
}

<div class="text-center">
    <h3>@ViewBag.Title</h3>
</div>
@if (Model.Count == 0)
{
    <div class="text-center">
        <p></p>
        <p></p>
        <p></p>
        <h5>No manufacturers in our data</h5>
        <a class="" asp-area="" asp-controller="City" asp-action="AddNewCity">Add new city</a>
        <p></p>
        <p></p>

    </div>
}
 @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
{
    <div class="text-center">
        <a class="" asp-area="" asp-controller="City" asp-action="AddNewCity">Add new city</a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Continent</th>
                <th scope="col">Country</th>
                <th scope="col">City</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>

            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Continent</td>
                    <td>@Model[i].Country</td>
                    <td>@Model[i].CityName</td>
                    <td>
                        <a asp-controller="City" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <a asp-controller="City" asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            </tbody>
        }
    </table>
    
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Continent</th>
                <th scope="col">Country</th>
                <th scope="col">City</th>
                
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Continent</td>
                    <td>@Model[i].Country</td>
                    <td>@Model[i].CityName</td>
                </tr>
            </tbody>
        }
    </table>
}

Airport_App/Views/City/Edit.cshtml
@model AddNewCityModel
@{
    ViewData["Title"] = "Edit city";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="mb-3">
                <label asp-for="@Model.CountryId" class="form-label"> Select Country</label>
                <select asp-for="@Model.CountryId" class="form-control">
                    @foreach (var airport in Model.Countries)
                    {
                        <option value="@airport.Id">@airport.Name</option>
                    }
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save changes</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}