Airport_App/Controllers/CountryController.cs
using Airport_App_Core.Contracts;
using Airport_App_Core.Models.CountryModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Airport_App.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryService countryService;

        public CountryController(ICountryService _country)
        {
            countryService = _country;
        }

        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public IActionResult AddNewCountry()
        {
            AddNewCountryModel model = new AddNewCountryModel();
            model.Continents.Add("Europe");
            model.Continents.Add("Australia");
            model.Continents.Add("North_America");
            model.Continents.Add("South_America");
            model.Continents.Add("Africa");
            model.Continents.Add("Asia");
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> AddNewCountry(AddNewCountryModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AddNewCountry));
            }

            var isThere = countryService.CheckIfExist(model);
            if (isThere == true)
            {
                return RedirectToAction(nameof(AddNewCountry));
            }
            await countryService.AddNewCountry(model);

            return RedirectToAction(nameof(AllCountries));
        }

        public async Task<IActionResult> AllCountries()
        {
            return View(await countryService.GetAllCountries()) ;
        }

        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Edit (int id)
        {
            var result = await countryService.FindCountry(id);
            result.Continents.Add("Europe");
            result.Continents.Add("Australia");
            result.Continents.Add("North_America");
            result.Continents.Add("South_America");
            result.Continents.Add("Africa");
            result.Continents.Add("Asia");
            return View(result);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Edit(AddNewCountryModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllCountries));
            }

            var isThere = countryService.CheckIfExist(model);
            if (isThere == true)
            {
                return RedirectToAction(nameof(AllCountries));
            }

            await countryService.SaveChangesAsync(model);
            return RedirectToAction(nameof(AllCountries));
        }

        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Delete(int id)
        {
            await countryService.Delete(id);
            return RedirectToAction(nameof(AllCountries));
        }
    }
}

Airport_App/Views/Country/AddNewCountry.cshtml
@model AddNewCountryModel
@{
    ViewData["Title"] = "Add new country";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <p></p>
            <p></p>

            <div class="mb-3">
            <label asp-for="@Model.ContinentId" class="form-label">Origin</label>
            <select asp-for="@Model.ContinentId" class="form-control">
                @foreach (var country in Model.Continents)
                {
                    <option value="@country">@country</option>
                }
            </select>
            <span asp-validation-for="ContinentId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Airport_App/Views/Country/AllCountries.cshtml
@model List<CountryViewModel>
@{
    ViewData["Title"] = "All countries";
}

<div class="text-center">
    <h3>Countries</h3>
</div>
@if (Model.Count == 0)
{
    <div class="text-center">
        <p></p>
        <p></p>
        <p></p>
        <h5>No manufacturers in our data</h5>
        <a class="" asp-area="" asp-controller="Country" asp-action="AddNewCountry">Add new Country</a>
        <p></p>
        <p></p>

    </div>
}
@if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
{
    <div class="text-center">
        <a class="" asp-area="" asp-controller="Country" asp-action="AddNewCountry">Add new Country</a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Continent</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Continent</td>
                    <td>
                        <a asp-controller="Country" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <a asp-controller="Country" asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            </tbody>
        }
    </table>
    
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Continent</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Continent</td>
                    
                </tr>
            </tbody>
        }
    </table>
}

Airport_App/Views/Country/Edit.cshtml
@model AddNewCountryModel
@{
    ViewData["Title"] = "Edit country";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <p></p>
            <p></p>

            <div class="mb-3">
                <label asp-for="@Model.ContinentId" class="form-label">Origin</label>
                <select asp-for="@Model.ContinentId" class="form-control">
                    @foreach (var country in Model.Continents)
                    {
                        <option value="@country">@country</option>
                    }
                </select>
                <span asp-validation-for="ContinentId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save changes</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}