Airport_App/Controllers/AirportController.cs
using Airport_App_Core.Contracts;
using Airport_App_Core.Models.AirportModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Airport_App.Controllers
{
    public class AirportController : Controller
    {
        private readonly IAirportService airportService;
        private readonly ICityService cityService;

        public AirportController(
            IAirportService _airportService,
            ICityService _city)
        {
            airportService = _airportService;
            cityService = _city;
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddNewAirport()
        {
            AddNewAirportModel model = new AddNewAirportModel()
            {
                Cityies = await cityService.GetAllCities()
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddNewAirport(AddNewAirportModel port)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AddNewAirport));
            }
            var isThere = airportService.CheckIfExist(port);
            if (isThere == true) 
            {
                return RedirectToAction(nameof(AddNewAirport));
            }

            await airportService.AddNewAirport(port);

            return RedirectToAction(nameof(AllAirports));
        }

        public async Task<IActionResult> AllAirports()
        {
            return View(await airportService.GetAllAirports());
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var airport = await airportService.FindAirport(id);
            airport.Cityies = await cityService.GetAllCities();
            return View(airport);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(AddNewAirportModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllAirports));
            }

            var isThere = airportService.CheckIfExist(model);
            if (isThere == true)
            {
                return RedirectToAction(nameof(AllAirports));
            }

            await airportService.SaveChangesAsync(model);
            return RedirectToAction(nameof(AllAirports));
        }

        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete (int id)
        {
            await airportService.DeleteAsync(id);
            return RedirectToAction(nameof(AllAirports));
        }

    }
}

Airport_App/Views/Airport/AddNewAirport.cshtml
@model AddNewAirportModel
@{
    ViewData["Title"] = "Add new airport";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="mb-3">
                <label asp-for="@Model.CityId" class="form-label"> Select City</label>
                <select asp-for="@Model.CityId" class="form-control">
                    @foreach (var airport in Model.Cityies)
                    {
                        <option value="@airport.Id">@airport.Name</option>
                    }
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.AirportCode" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.AirportCode"></label>
                <span asp-validation-for="@Model.AirportCode" class="text-danger"></span>
            </div>


            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Airport_App/Views/Airport/AllAirports.cshtml
@model List<DisplayAirportModel>
@{
    ViewData["Title"] = "All Airports";
}

<div class="text-center">
    <h3>Airports</h3>
</div>
@if (Model.Count == 0)
{
    <div class="text-center">
        <p></p>
        <p></p>
        <p></p>
        <h5>No manufacturers in our data</h5>
        <a class="" asp-area="" asp-controller="Airport" asp-action="AddNewAirport">Add new airport</a>
        <p></p>
        <p></p>

    </div>
}
 @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
{
    <div class="text-center">
        <a class="" asp-area="" asp-controller="Airport" asp-action="AddNewAirport">Add new airport</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Country</th>
                <th scope="col">City</th>
                <th scope="col">Name</th>
                <th scope="col">Code</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Country</td>
                    <td>@Model[i].City</td>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Code</td>
                    <td>
                        <a asp-controller="Airport" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <a asp-controller="Airport" asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            </tbody>
        }
    </table>
    
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Country</th>
                <th scope="col">City</th>
                <th scope="col">Name</th>
                <th scope="col">Code</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Country</td>
                    <td>@Model[i].City</td>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Code</td>
                    
                </tr>
            </tbody>
        }
    </table>
}

Airport_App/Views/Airport/Edit.cshtml
@model AddNewAirportModel
@{
    ViewData["Title"] = "Edit airport";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="mb-3">
                <label asp-for="@Model.CityId" class="form-label"> Select City</label>
                <select asp-for="@Model.CityId" class="form-control">
                    @foreach (var airport in Model.Cityies)
                    {
                        <option value="@airport.Id">@airport.Name</option>
                    }
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name"></label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.AirportCode" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.AirportCode"></label>
                <span asp-validation-for="@Model.AirportCode" class="text-danger"></span>
            </div>


            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save changes</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}