Airport_App/Controllers/AirplaneController.cs
using Airport_App_Core.Contracts;
using Airport_App_Core.Models.AirplaneModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Airport_App.Controllers
{
    public class AirplaneController : Controller
    {
        private readonly IAirplaneService airplaneService;
        private readonly IManufacturerServce manufacturerServce;

        public AirplaneController(
            IAirplaneService _airplaneService,
            IManufacturerServce _manufacturerServce)
        {
            airplaneService = _airplaneService;
            manufacturerServce = _manufacturerServce;
        }

        [HttpGet]
        public async Task<IActionResult> FlightsPerAirplane()
        {
            SearchAirplaneModel model = new SearchAirplaneModel()
            {
                Aircrafts = await airplaneService.AddAllAircrafts(),

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FlightsPerAirplane(SearchAirplaneModel model)
        {
            List<DisplayAirplaneFlightsModel> result = await airplaneService.GetFlightsPerPlane(model.AircraftId);
            return View(nameof(Display), result);
        }

        public IActionResult Display(List<DisplayAirplaneFlightsModel> model)
        {
            return View(model);
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddPLane()
        {
            AddNewPlane model = new AddNewPlane()
            {
                Manufacturers = await manufacturerServce.GetAllCompanies()
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddPLane(AddNewPlane plane)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await airplaneService.AddAircraft(plane);

            return RedirectToAction(nameof(AllJets));
        }

        public async Task<IActionResult> AllJets()
        {
            return View(await airplaneService.GetAllPLanes());
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit (int id)
        {
            var plane = await airplaneService.FindJet(id);
            plane.Manufacturers = await manufacturerServce.GetAllCompanies();
            return View(plane);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(AddNewPlane plane)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllJets));
            }
            await airplaneService.SaveChangesAsync(plane);
            return RedirectToAction(nameof(AllJets));
        }
        [Authorize]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            
            await airplaneService.DeleteAsync(id);
            return RedirectToAction(nameof(AllJets));
        }


    }
}

Airport_App/Controllers/FlightController.cs
using Airport_App_Core.Contracts;
using Airport_App_Core.Models.FlightModels;
using Airport_App_Core.Models.TicketModels;
using Airport_App_Core.Services;
using Airport_App_Structure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Airport_App.Controllers
{
    public class FlightController : Controller
    {
        private readonly AirportDb data;
        private readonly IFlightsService flightsService;
        private readonly ICountryService countryService;
        private readonly ICityService cityService;
        private readonly IAirportService airportService;
        private readonly IAirplaneService airplaneService;

        public FlightController(
            AirportDb _data,
            IFlightsService _flightsService,
            ICountryService _countryService,
            IAirportService _airportService,
            ICityService _cityService,
            IAirplaneService _airplaneService
            )
        {
            data = _data;
            flightsService = _flightsService;
            countryService = _countryService;
            airportService = _airportService;
            cityService = _cityService;
            airplaneService = _airplaneService;
        }

        public async Task<IActionResult> LastFive()
        {
            
            return View(await flightsService.TakeLastFive());
        }

        [HttpGet]
        public async Task<IActionResult> Search ()
        {
            SearchFlightModel model = new SearchFlightModel()
            {
                DepartureCity = await cityService.GetAllCities(),
                ArrivalCity = await cityService.GetAllCities(),
                DepartureDate = DateTime.UtcNow

            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Search(SearchFlightModel model)
        {

            var result = await flightsService.SearchFlight(model);
            return View(nameof(Display), result);
        }

        public IActionResult Display(List<DisplayFlightModel> model)
        {
           
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> FilterByCountry()
        {
            FilterByCountryModel model = new FilterByCountryModel()
            {
                Countries = await countryService.AddAllCountries()
            };
            

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> FilterByCountry(int countryId)
        {
            var result = await flightsService.AllByCountryDeparture (countryId);
            return View(nameof(Display), result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> FilterByDepartureAirport()
        {
            FilterByDepartureAirportModel model = new FilterByDepartureAirportModel()
            {
                Airports = await airportService.AddAllAirports()
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> FilterByDepartureAirport(int airportId)
        {
            var result = await flightsService.FilterByDepartureAirport(airportId);
            return View(nameof(Display), result);
        }

        [Authorize]
        public IActionResult Filter()
        {
            return View();
        }

        public async Task<IActionResult> AllFlights()
        {
            var result = await flightsService.AllFlights();
            return View(result); 
        }

        
        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> Edit(int id)
        {
            

            var result  = await flightsService.FindFlight(id);

            result.Departures = await airportService.AddAllAirports();
            result.ArrivalAirport = await airportService.AddAllAirports();
            //result.DepartureTime = DateTime.Parse(depart.ToString("dd-MM-yyyy, HH:mm"));
            //result.ArivalTime = DateTime.Parse(arrive.ToString("dd-MM-yyyy, HH:mm"));
            result.AirplaneModel = await airplaneService.AddPlanes();
            
            return View(result);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]

        public async Task<IActionResult> Edit(AddNewFlightModel addFlight)
        {
            
            await flightsService.SaveChangesAsync(addFlight);
            return RedirectToAction(nameof(AllFlights));

        }


        [HttpGet]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> AddNewFlight()
        {
            
            DateTime depart = DateTime.UtcNow;
            DateTime arrive = depart.AddMinutes(60);


            AddNewFlightModel addFlight = new AddNewFlightModel()
            {
                Departures = await airportService.AddAllAirports(),
                ArrivalAirport = await airportService.AddAllAirports(),
                AirplaneModel = await airplaneService.AddPlanes(),
                DepartureTime = DateTime.Parse(depart.ToString("dd-MM-yyyy, HH:mm")),
                ArivalTime = DateTime.Parse(arrive.ToString("dd-MM-yyyy, HH:mm")),

            };

            return View(addFlight);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Policy = "AdminsOnly")]
        public async Task<IActionResult> AddNewFlight(AddNewFlightModel addFlight)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(AllFlights));
            }
            
            var differentAirport = flightsService.CheckAirports(addFlight);
            if (differentAirport == false)
            {
                return RedirectToAction(nameof(AllFlights));
            }

            var checkDifferentDates = flightsService.CheckDates(addFlight);
            if (checkDifferentDates == false)
            {
                return RedirectToAction(nameof(AllFlights));
            }


            await flightsService.AddNewFlight(addFlight);

            return RedirectToAction(nameof(AllFlights));
            
        }

        [HttpGet]
        [Authorize]
        public async Task< IActionResult> BuyTickets(int id)
        {

            NumberTicketsModel numberPassengers = new NumberTicketsModel();
            numberPassengers.FlightId = id;
            numberPassengers.Flight.Add(await flightsService.GetFlight(id));
            return View(numberPassengers);
        }

        [HttpPost]
        [Authorize]
        public IActionResult BuyTickets(NumberTicketsModel numberPassengers)
        {
            var available = flightsService.CheckIfThereAreEnoughTickets(numberPassengers);
            if (available == false)
            {
                return RedirectToAction(nameof(BuyTickets), numberPassengers.FlightId);
            }
            return RedirectToAction("AddPassengers", "Passenger", numberPassengers);
        }
    }
}

Airport_App/Views/Airplane/AddPLane.cshtml
@model AddNewPlane
@{
    ViewData["Title"] = "Add new airplane";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="@Model.ManufacturerId" class="form-label">Manufacturer</label>
                <select asp-for="@Model.ManufacturerId" class="form-control">
                    @foreach (var manifacturer in Model.Manufacturers)
                    {
                        <option value="@manifacturer.Id">@manifacturer.Name</option>
                    }
                </select>
                <span asp-validation-for="ManufacturerId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.Model" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Model"></label>
                <span asp-validation-for="@Model.Model" class="text-danger"></span>
            </div>
            <p></p>
            <p></p>
            <div class="form-floating">
                <input asp-for="@Model.Capacity" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Capacity"></label>
                <span asp-validation-for="@Model.Capacity" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Airport_App/Views/Airplane/AllJets.cshtml
@model List<DisplayAirplaneModel>
@{
    ViewData["Title"] = "All planes";
}

<div class="text-center">
    <h3>Airplanes</h3>
</div>
@if (Model.Count == 0)
{
    <div class="text-center">
        <p></p>
        <p></p>
        <p></p>
        <h5>No planes in our data</h5>
        <a class="" asp-area="" asp-controller="Airplane" asp-action="AddPlane">Add new plane</a>
        <p></p>
        <p></p>

    </div>
}
@if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
{
    <div class="text-center">
        <a class="" asp-area="" asp-controller="Airplane" asp-action="AddPlane">Add new plane</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Capacity</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Manufacturer</td>
                    <td>@Model[i].Model</td>
                    <td>@Model[i].Seats</td>
                    <td>
                        <a asp-controller="Airplane" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                    </td>
                    <td>
                        <a asp-controller="Airplane" asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Detele</a>
                    </td>

                </tr>
            </tbody>
        }

    </table>

    
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
                <th scope="col">Capacity</th>
                
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Manufacturer</td>
                    <td>@Model[i].Model</td>
                    <td>@Model[i].Seats</td>
                    
                </tr>
            </tbody>
        }
            
    </table>
    
}

Airport_App/Views/Airplane/Display.cshtml
@model List<DisplayAirplaneFlightsModel>
@{
    ViewData["Title"] = "Result";
}

<div class="text-center">
    <h3>Fligths</h3>
</div>
@if (Model.Count == 0)
{
    <div class="text-center">
        <p></p>
        <p></p>
        <p></p>
        <h5>Nothing found</h5>
        <a class="" asp-area="" asp-controller="Flight" asp-action="Search">Search for flight</a>
        <p></p>
        <p></p>
        <a class="" asp-area="" asp-controller="Flight" asp-action="Filter">Filter flights</a>

    </div>
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Manufacturer</th>
                <th scope="col">Model</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            int number = @i + 1;
            <tbody>
                <tr>
                    <td>@number</td>
                    <td>@Model[i].Manufacturer</td>
                    <td>@Model[i].Model.ToString()</td>

                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Departure City</th>
                                <th scope="col">Departure Airport</th>
                                <th scope="col">Arrival city</th>
                                <th scope="col">Arrival Airport</th>
                                <th scope="col">Price</th>
                                <th scope="col">Departure</th>
                                <th scope="col">Arrive</th>
                                <th scope="col">Buy</th>
                            </tr>
                        </thead>
                        @for(int j = 0; j< Model[i].Flights.Count; j ++)
                        {
                        <tbody>
                                <tr>
                                    <td>@number</td>
                                    <td>@Model[i].Flights[j].DepartureCity</td>
                                    <td>@Model[i].Flights[j].DepartureAirport.ToString()</td>
                                    <td>@Model[i].Flights[j].DestinationCity</td>
                                    <td>@Model[i].Flights[j].DestinationAirport.ToString()</td>
                                    <td>@Model[i].Flights[j].Price $</td>
                                    <td>@Model[i].Flights[j].StartDate</td>
                                    <td>@Model[i].Flights[j].ArriveDate</td>
                                    <td>
                                        <a asp-controller="Flight" asp-action="BuyTickets" asp-route-id="@Model[i].Flights[j].Id" class="btn btn-warning">Buy</a>
                                    </td>
                                   </tr>
                        </tbody>
                        }
                    </table>
                </tr>
            </tbody>
        }
    </table>
}

Airport_App/Views/Airplane/Edit.cshtml
@model AddNewPlane
@{
    ViewData["Title"] = "Edit airplane";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3 class="text-center">@ViewBag.title</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="@Model.ManufacturerId" class="form-label">Manufacturer</label>
                <select asp-for="@Model.ManufacturerId" class="form-control">
                    @foreach (var manifacturer in Model.Manufacturers)
                    {
                        <option value="@manifacturer.Id">@manifacturer.Name</option>
                    }
                </select>
                <span asp-validation-for="ManufacturerId" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <div class="form-floating">
                <input asp-for="@Model.Model" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Model"></label>
                <span asp-validation-for="@Model.Model" class="text-danger"></span>
            </div>
            <p></p>
            <p></p>
            <div class="form-floating">
                <input asp-for="@Model.Capacity" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Capacity"></label>
                <span asp-validation-for="@Model.Capacity" class="text-danger"></span>
            </div>

            <p></p>
            <p></p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save changes</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Airport_App/Views/Airplane/FlightsPerAirplane.cshtml
@model SearchAirplaneModel
@{
    ViewData["Title"] = "Search Airplane";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3>Select model</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="mb-3">
                <label asp-for="@Model.AircraftId" class="form-label">Airplane Model</label>
                <select asp-for="@Model.AircraftId" class="form-control">
                    @foreach (var airplane in Model.Aircrafts)
                    {
                        <option value="@airplane.Id">@airplane.Model </option>
                    }
                </select>
                <span asp-validation-for="AircraftId" class="text-danger"></span>
            </div>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Search</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}